#!/bin/bash

set -eu
LSP_SERVER_BIN=${LSP_SERVER_BIN:-bin/Debug/net5.0/MyLspServer}

send() {
    BODY="$1"
    LEN=$(printf "%s\n" "$BODY" | wc -c)
    printf "Content-Length: %d\r\n\r\n%s\n" "$LEN" "$BODY"
}

{
    send '{"method": "initialize", "id": 1}'
    send '{"method": "initialized"}'
    send '{"method": "shutdown", "id": 2}'
    send '{"method": "exit"}'
} | "$LSP_SERVER_BIN"
